# version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  ml_service:
    depends_on:
      - minio
    image: facerecognition2:6
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      STORAGE_ACESS_KEY: minioadmin
      STORAGE_SECRET_KEY: minioadmin
      STORAGE_DNS: "minio:9000"

volumes:
  minio_data:
